# Generated by Django 5.0.4 on 2024-04-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True)),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
