# Generated by Django 5.0.4 on 2024-04-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Product'), (2, 'User')]),
        ),
    ]
