# Generated by Django 5.0.4 on 2024-04-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0006_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
